### ISSUE TITLE
Improve readability of 'ease' module.

### ISSUE THREAD

**Issue by zummenix** [PistonDevelopers/interpolation#16]
Currently we have many noise due to float conversion by `FromPrimitive::from_f64(<number>)` calls. I have some options to discuss:
1. Use shorthand syntax to convert float scalar to generic float type. See discussion #8
2. Make `Ease` trait with ease functions (like `std::num::Float`) and implement it for `f32` and `f64` types using macro:

``` rust
pub trait Ease {
    fn calc(self, f: EaseFunction) -> Self;

    fn quadratic_in(self) -> Self;
    fn quadratic_out(self) -> Self;
    fn quadratic_in_out(self) -> Self;
// ...
}
```
1. Stick with current implementation.

I more like second variant, because first variant doesn't solve problem fully.

**Comment by bvssvni** [comment]
A trait sounds good.
