### ISSUE TITLE
Remove unnecessary casts like `<Self as Spatial>::Scalar`

### ISSUE THREAD

**Issue by zummenix** [PistonDevelopers/interpolation#37]
https://github.com/PistonDevelopers/interpolation/blob/feccc5ae5d2f52df42a3496fd180a0dc2fda50b7/src/spatial.rs#L13
As I understand we can remove it safely? Just leave `Self::Scalar`

**Comment by bvssvni** [comment]
Yeah, this was probably before Rust got that feature.
